### ISSUE TITLE
insert or update on table "inquiry_sample" violates foreign key constraint

### ISSUE THREAD

**Issue by yorickdewid** [Laixer/FunderMaps#884]
```
[fundermaps-app-prod] [2024-07-08 12:59:24]       Npgsql.PostgresException (0x80004005): 23503: insert or update on table "inquiry_sample" violates foreign key constraint "inquiry_sample_building_fkey"
[fundermaps-app-prod] [2024-07-08 12:59:24]       
[fundermaps-app-prod] [2024-07-08 12:59:24]       DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
[fundermaps-app-prod] [2024-07-08 12:59:24]          at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
[fundermaps-app-prod] [2024-07-08 12:59:24]          at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
[fundermaps-app-prod] [2024-07-08 12:59:24]          at Npgsql.NpgsqlDataReader.<ReadMessage>g__ReadMessageSequential|49_0(NpgsqlConnector connector, Boolean async)
[fundermaps-app-prod] [2024-07-08 12:59:24]          at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
[fundermaps-app-prod] [2024-07-08 12:59:24]          at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
[fundermaps-app-prod] [2024-07-08 12:59:24]          at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
[fundermaps-app-prod] [2024-07-08 12:59:24]          at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
[fundermaps-app-prod] [2024-07-08 12:59:24]          at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken)
[fundermaps-app-prod] [2024-07-08 12:59:24]          at FunderMaps.Data.DbContext.ScalarAsync[TResult](Boolean resultGuard) in /source/src/FunderMaps.Data/DbContext.cs:line 203
[fundermaps-app-prod] [2024-07-08 12:59:24]         Exception data:
[fundermaps-app-prod] [2024-07-08 12:59:24]           Severity: ERROR
[fundermaps-app-prod] [2024-07-08 12:59:24]           SqlState: 23503
[fundermaps-app-prod] [2024-07-08 12:59:24]           MessageText: insert or update on table "inquiry_sample" violates foreign key constraint "inquiry_sample_building_fkey"
[fundermaps-app-prod] [2024-07-08 12:59:24]           Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
[fundermaps-app-prod] [2024-07-08 12:59:24]           SchemaName: report
[fundermaps-app-prod] [2024-07-08 12:59:24]           TableName: inquiry_sample
[fundermaps-app-prod] [2024-07-08 12:59:24]           ConstraintName: inquiry_sample_building_fkey
[fundermaps-app-prod] [2024-07-08 12:59:24]           File: ri_triggers.c
[fundermaps-app-prod] [2024-07-08 12:59:24]           Line: 2608
[fundermaps-app-prod] [2024-07-08 12:59:24]           Routine: ri_ReportViolation
```

**Comment by yorickdewid** [comment]
Know issue: when the ClientApp provides a inquiry_sample with a non-existing building id.
